version: "3.8"

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra_user_logs
    ports:
      - "9042:9042" # CQL port only
    environment:
      - CASSANDRA_CLUSTER_NAME=UserLogCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=128
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./cassandra/init:/docker-entrypoint-initdb.d
    networks:
      - cassandra_network
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 2m

  cassandra-web:
    image: ipushc/cassandra-web
    container_name: cassandra_web_ui
    ports:
      - "3001:3000"
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - cassandra_network

volumes:
  cassandra_data:

networks:
  cassandra_network:
    driver: bridge
